### ISSUE TITLE
Particular threads don't work

### ISSUE THREAD

**Issue by tayzuz** [JasonLovesDoggo/RedditVideoMakerBot#103]
**Describe the bug**
Sometimes some threads just won't work while most others are fine

Traceback (most recent call last):
  File "C:\Users\yanni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\yanni\RedditVideoMakerBot-master\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\yanni\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\yanni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JasonLovesDoggo** [comment]
Please use the main repo
