### ISSUE TITLE
sox error

### ISSUE THREAD

**Issue by lesterrar** [JasonLovesDoggo/RedditVideoMakerBot#22]
C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1>python main.py
'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

   Thanks for using this tool! 😊 Feel free to contribute to this project on GitHub! (JasonLovesDoggo/RedditVideoMakerBot). If you have any questions, feel free to
                                                         reach out to me on Twitter or submit a GitHub issue.

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from environment variable config
subreddit thread is: What are some golden Reddit threads that everyone should read at least once?
(if you dont like this, you can change it by exiting and rerunning the program)
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files 🎶                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ----------------------------------------
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/0.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1\video_creation\voices.py", line 38, in save_text_to_mp3
    length += MP3(f"assets/temp/mp3/{idx}.mp3").info.length
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/0.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1\main.py", line 39, in <module>
    main()
  File "C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1\main.py", line 30, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1\video_creation\voices.py", line 40, in save_text_to_mp3
    length = sox.file_info.duration(f"assets/temp/mp3/{idx}.mp3")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sox\file_info.py", line 121, in duration
    validate_input_file(input_filepath)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sox\file_info.py", line 248, in validate_input_file
    raise IOError(
OSError: input_filepath assets/temp/mp3/0.mp3 does not exist.

C:\Users\admin\Documents\GitHub\RedditVideoMakerBot1>

**Comment by ZENX0x2** [comment]
I get the same error 😢

**Comment by StopmotionSimonYT** [comment]
I get the same error
