### ISSUE TITLE
could not find match for ^\w+\W Error

### ISSUE THREAD

**Issue by Xiinergy** [JasonLovesDoggo/RedditVideoMakerBot#23]
This started happening after I downloaded the new version, it gives me this error when it starts downloading the background videos.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-master patched\RedditVideoMakerBot-master\main.py", line 39, in <module>
    main()
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-master patched\RedditVideoMakerBot-master\main.py", line 32, in main
    download_background()
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-master patched\RedditVideoMakerBot-master\video_creation\background.py", line 39, in download_background
    YouTube(uri).streams.filter(res="720p").first().download("assets/backgrounds",
  File "C:\Users\Aigars\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Aigars\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Aigars\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Aigars\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

**Comment by IdkHowAreYOU** [comment]
I have the exact same problem right now

**Comment by nenoviktor** [comment]
same

**Comment by MDAmirPathan** [comment]
Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33** 
from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
hope That Solves Issue

**Comment by IdkHowAreYOU** [comment]
it worked 👍

**Comment by binbohrawa** [comment]
@MDAmirPathan Thanks

**Comment by nenoviktor** [comment]
> Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33**
> from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
> hope That Solves Issue

where does one find this?

**Comment by IdkHowAreYOU** [comment]
You need to find the cypher.py file.
You can find it by finding the lib folder, and then site-packages, then pytube, and in that folder there should be a file called cipher.py
`lib\site-packages\pytube\cipher.py"`

**Comment by nenoviktor** [comment]
do u happen to know where these folders are on Mac

**Comment by IdkHowAreYOU** [comment]
I unfortunately dont use Mac, sorry

**Comment by JasonLovesDoggo** [comment]
see https://github.com/elebumm/RedditVideoMakerBot/issues/147

**Comment by nenoviktor** [comment]
> Go to last error path in ur console **site-packages\pytube\cipher.py line Number 30 or 33**
> from `var_regex = re.compile(r"^\w+\W")` change to `var_regex = re.compile(r"^\$*\w+\W")`
> hope That Solves Issue

Found it and edited it but im still getting the issue
