### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'title'

### ISSUE THREAD

**Issue by IdkHowAreYOU** [JasonLovesDoggo/RedditVideoMakerBot#27]
I get this error:
`Traceback (most recent call last):
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 43, in <module>
    main()
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 33, in main
    reddit_object = get_obj()
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 25, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\reddit\subreddit.py", line 45, in get_subreddit_threads
    submission = check_done(submission)
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\utils\videos.py", line 21, in check_done
    return get_subreddit_threads()  # recursive func
  File "C:\Users\vict9015\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\reddit\subreddit.py", line 48, in get_subreddit_threads
    f'subreddit thread is: {submission.title}\n (if you dont like this, you can change it by exiting and '
AttributeError: 'dict' object has no attribute 'title'`

After "Getting subreddit threads..."                          

Any help?

**Comment by StopmotionSimonYT** [comment]
I get the same error

**Comment by snappyy** [comment]
me too

**Comment by JasonLovesDoggo** [comment]
will be fixed Along with the SoX error
