### ISSUE TITLE
FileNotFoundError when launching main.py

### ISSUE THREAD

**Issue by Xiinergy** [JasonLovesDoggo/RedditVideoMakerBot#3]
Traceback (most recent call last):
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-mastertts\RedditVideoMakerBot-master\main.py", line 39, in <module>
    main()
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-mastertts\RedditVideoMakerBot-master\main.py", line 18, in main
    cleanup()
  File "C:\Users\Aigars\Desktop\RedditVideoMakerBot-mastertts\RedditVideoMakerBot-master\utils\cleanup.py", line 16, in cleanup
    for file in os.listdir('./assets/temp/mp3'):
FileNotFoundError: [WinError 3] The system cannot find the path specified: './assets/temp/mp3'

**Comment by k3lux** [comment]
make the folder assets/temp/mp3 and assets/temp/mp4

**Comment by JasonLovesDoggo** [comment]
> > make the folder assets/temp/mp3 and assets/temp/mp4
> 
> This worked, turns out I just misspelled "assets" :D

happened to me while I was making the tts lib
