### ISSUE TITLE
Multiplie Feature requests for overall better video

### ISSUE THREAD

**Issue by jacobjake1** [JasonLovesDoggo/RedditVideoMakerBot#55]
I just made a video and I noticed some things that could make it a lot better;

- When the video starts off it takes a screenshot of the entire post + text and only reads the headline, doesn't make sense would just be better to show and read the headline

- Be able to sort comments by upvotes, all the comments I just pulled had like 3 upvotes and some had nothing to do with the actual post

- There's this weird 5 second pause at the end of the video where nothing is happening 

- The background video does nothing; it's frozen on a single frame (bug?) 

https://user-images.githubusercontent.com/4533823/172076719-a6bdab86-c2de-4e27-a8f4-dbd856d6e7fa.mp4

**Comment by JasonLovesDoggo** [comment]
Suggestions noted.

**Comment by JasonLovesDoggo** [comment]
> The background video does nothing; it's frozen on a single frame (bug?)

I've never once witnessed that. 
try recloning

**Comment by JasonLovesDoggo** [comment]
> There's this weird 5 second pause at the end of the video where nothing is happening

fixed.

**Comment by jacobjake1** [comment]
> > There's this weird 5 second pause at the end of the video where nothing is happening
> 
> fixed.

Im running your new fork and im getting this now....?

 C:\Users\jacob\Desktop\red>python3 main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\jacob\Desktop\red\reddit\subreddit.py", line 8, in <module>
    from utils.subreddit import get_hottest_undone
  File "C:\Users\jacob\Desktop\red\utils\subreddit.py", line 1, in <module>
    from typings import List
ModuleNotFoundError: No module named 'typings'

C:\Users\jacob\Desktop\red>pip install typings
ERROR: Could not find a version that satisfies the requirement typings (from versions: none)
ERROR: No matching distribution found for typings

C:\Users\jacob\Desktop\red>

**Comment by JasonLovesDoggo** [comment]
That's from a PR let me fix that real quick

**Comment by JasonLovesDoggo** [comment]
> > > There's this weird 5 second pause at the end of the video where nothing is happening
> > 
> > fixed.
> 
> Im running your new fork and im getting this now....?
> 
>  C:\Users\jacob\Desktop\red>python3 main.py
> Traceback (most recent call last):
>   File "main.py", line 6, in <module>
>     from reddit.subreddit import get_subreddit_threads
>   File "C:\Users\jacob\Desktop\red\reddit\subreddit.py", line 8, in <module>
>     from utils.subreddit import get_hottest_undone
>   File "C:\Users\jacob\Desktop\red\utils\subreddit.py", line 1, in <module>
>     from typings import List
> ModuleNotFoundError: No module named 'typings'
> 
> C:\Users\jacob\Desktop\red>pip install typings
> ERROR: Could not find a version that satisfies the requirement typings (from versions: none)
> ERROR: No matching distribution found for typings
> 
> C:\Users\jacob\Desktop\red>

Fixed
