### ISSUE TITLE
mp3 error on the last update

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#71]
whenever I run the it it says
`  File "C:\Python310\lib\site-packages\sox\combine.py", line 228, in set_input_format
    raise ValueError(
ValueError: file_type elements must be one of []`
at the mp3 section

**Comment by JasonLovesDoggo** [comment]
Could you provide the full trace back?

**Comment by brokencommit** [comment]
I got the same error

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 40, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "E:\RedditBot\GoodTTS\video_creation\voices.py", line 29, in save_text_to_mp3
    ttttsw.tts(
  File "E:\RedditBot\GoodTTS\video_creation\TTSwrapper.py", line 94, in tts
    cbn.set_input_format(file_type=['mp3'])
  File "C:\Users\XXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sox\combine.py", line 228, in set_input_format
    raise ValueError(
ValueError: file_type elements must be one of []
```

**Comment by JasonLovesDoggo** [comment]
And all the audio files in the temp directory are .mp3 correct?

**Comment by brokencommit** [comment]
it seems to have ran before the mp3 files were generated

**Comment by JasonLovesDoggo** [comment]
Hmm I can't fix that tonight but I can try tomorrow

**Comment by brokencommit** [comment]
I will take a stab at it :) See what I can figure out

**Comment by JasonLovesDoggo** [comment]
> I will take a stab at it :) See what I can figure out


A hint I can give would be to look at all the places where the function is called.

**Comment by justexistingnow** [comment]
Hi! Sorry I didn't get a notification, heres the full thing
`Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files 🎶                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\zaid-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\main.py", line 62, in <module>
    main()
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\main.py", line 40, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\video_creation\voices.py", line 29, in save_text_to_mp3
    ttttsw.tts(
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\video_creation\TTSwrapper.py", line 94, in tts
    cbn.set_input_format(file_type=['mp3'])
  File "C:\Python310\lib\site-packages\sox\combine.py", line 228, in set_input_format
    raise ValueError(
ValueError: file_type elements must be one of []`

**Comment by JasonLovesDoggo** [comment]
Will work on this tomorrow

**Comment by JasonLovesDoggo** [comment]
Will work on this tomorrow

**Comment by stopmoclay** [comment]
I'm also getting this error

**Comment by JasonLovesDoggo** [comment]
> I will take a stab at it :) See what I can figure out
> 

Any updates?
