### ISSUE TITLE
Error when trying to change the background video (fixed, user error)

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#72]
Changed the code, this error came out
`Traceback (most recent call last):
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason multi normal\main.py", line 62, in <module>
    main()
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason multi normal\main.py", line 42, in main
    download_background()
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason multi normal\video_creation\background.py", line 33, in download_background
    for uri, filename, credit in background_options:
ValueError: not enough values to unpack (expected 3, got 0)`
the background video downloaded fine and is in the assets folder but the error keeps happening

**Comment by justexistingnow** [comment]
this was user error, I fixed it sorry.

**Comment by JasonLovesDoggo** [comment]
All good
(You forgot the file name and credit)
