### ISSUE TITLE
No module named 'sox' - Sox is installed

### ISSUE THREAD

**Issue by jacob99200** [JasonLovesDoggo/RedditVideoMakerBot#79]
Traceback (most recent call last):
  File "Directory\main.py", line 12, in <module>
    from video_creation.voices import save_text_to_mp3
  File "Directory\BetterRedditBot\video_creation\voices.py", line 4, in <module>
    import sox
ModuleNotFoundError: No module named 'sox'

I have Sox installed, but it's through out this when running main.py

**Comment by StopmotionSimonYT** [comment]
I got the same error but when I installed SoX with `pip3 install sox`. It worked

**Comment by jacob99200** [comment]
> I got the same error but when I installed SoX with `pip3 install sox`. It worked

That worked perfectly!

Thank you

**Comment by StopmotionSimonYT** [comment]
No problem!

**Comment by StopmotionSimonYT** [comment]
Can you mark the issue as solved?
