### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by LeonNussbaum** [JasonLovesDoggo/RedditVideoMakerBot#91]
Hello I got this error 

![grafik](https://user-images.githubusercontent.com/91377653/173223126-3b202df4-a015-4276-9cb4-61beb1692402.png)

```
Traceback (most recent call last):
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\main.py", line 62, in <module>
    main()
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\main.py", line 42, in main
    download_background()
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\video_creation\background.py", line 37, in download_background
    YouTube(uri).streams.filter(res="1080p").first().download(
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 555, in error
    result = self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
```

**Comment by StopmotionSimonYT** [comment]
I don't know a fix for this but you can install the YouTube video manually. I use 4k video downloader for windows but there are also websites for downloading. After downloading the video you need to change the name which is also in the background.py file.

**Comment by JasonLovesDoggo** [comment]
That's an issue with YouTube listen to what @StopmotionSimonYT said.

**Comment by JasonLovesDoggo** [comment]
Also @StopmotionSimonYT are you in the discord server?

**Comment by StopmotionSimonYT** [comment]
> Also @StopmotionSimonYT are you in the discord server?

No

**Comment by JasonLovesDoggo** [comment]
https://discord.gg/zDpsvQs3
It's Lewis's @StopmotionSimonYT

**Comment by StopmotionSimonYT** [comment]
Thanks, I joined

**Comment by LeonNussbaum** [comment]
> 

Thanks
